table:
  wait_before_refresh: 0.5
  refresh_per_second: 10
  title: "System Metrics :detective:"
  style: "magenta"
  columns:
    - name: "Category"
      justify: "left"
      no_wrap: True
      style: "blue"
    - name: "Metric"
      justify: "left"
      no_wrap: True
      style: "blue"
    - name: "Usage"
      justify: "left"
      no_wrap: True
      style: "green"
    - name: "Description"
      justify: "left"
      no_wrap: True
      style: "yellow"
categories:
  - name: ":brain: MEMORY"
    metrics:
      - name: "Used"
        description: "Total Ram currently in use by the system"
        function: "virtual_memory"
        attribute: "used"
        unit: "GB"
        show_percentage: True
      - name: "Active"
        description: "Ram actively being accessed by processes"
        function: "virtual_memory"
        attribute: "active"
        unit: "GB"
        show_percentage: True
      - name: "Swap"
        description: "Data moved to disk"
        function: "swap_memory"
        attribute: "used"
        unit: "GB"
        show_percentage: True
  - name: ":computer: CPU"
    metrics:
      - name: "Idle"
        description: "Percentage of time the CPU is not in use"
        function: "cpu_times_percent"
        attribute: "idle"
  - name: ":floppy_disk: Disk"
    metrics:
      - name: "Disk Usage"
        description: "Total disk space currently in use"
        function: "disk_usage"
        attribute: "used"
        unit: "GB"
        parameters:
        - "/"
  - name: ":globe_with_meridians: Network"
    metrics:
      - name: "Network Sent"
        description: "Total data sent over the network"
        function: "net_io_counters"
        attribute: "bytes_sent"
        unit: "MB"
      - name: "Network Recv"
        description: "Total data received over the network"
        function: "net_io_counters"
        attribute: "bytes_recv"
        unit: "MB"
